### ISSUE TITLE
Morning session review 6/Apr/2020.

### ISSUE THREAD

**Issue by SigmaSam** [emasdev/newyork-times-clone#2]
-Change the variables for direct code colors to avoid validation issues.

**Comment by asiimwedismas** [comment]
Since you used absolute to position the aside editor's picks, you should probably use a top value of at least 40% so it is always positioned halfway the first part of the article no matter how long or short the article is

**Comment by shubhsk88** [comment]
-- Fix the size of the font in the aside 
-- Somewhere the size of font-size of figcaption is large
-- Try to complete the footer bar
