### ISSUE TITLE
Morning Session  6th April Monday Issue Team Capricornus

### ISSUE THREAD

**Issue by harshdeepkanhai** [emasdev/newyork-times-clone#3]
create any issues for this project.

**Comment by SevlaMare** [comment]
-Aside is overlapping, can be fixed with float and position properties.
-In "The Theory of Inflation" you can use the whole image as one single background like the original.

**Comment by ghamtre** [comment]
Please add the footer using the footer tag so you don't have to use any custom properties to fix it at the bottom.

**Comment by ferbaco86** [comment]
- Congratulations on the project. Really well organized CSS
- On the "Theory of Inflation" section, it would be recommended to use the whole image as a background picture and structure the text accordingly
![Captura de Pantalla 2020-04-06 a la(s) 10 28 55](https://user-images.githubusercontent.com/52765379/78569622-e0c43480-77f1-11ea-98de-1aa1118cb18a.png)
